using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Windows.Forms;
using System.Xml;

namespace Dynamic.Script_8DA875B9994CCA2
{
	// Script generated by Pega Robot Studio 19.1.112.0
	// Please use caution when modifying class name, namespace or attributes
	[OpenSpan.TypeManagement.DynamicTypeAttribute()]
	[OpenSpan.Design.ComponentIdentityAttribute("Script-8DA875B9994CCA2")]
	public sealed class Script
	{
		public int GetFileCount(string SourcePath)
		{
			
			System.IO.DirectoryInfo dir = new System.IO.DirectoryInfo("SourcePath");
			int count = dir.GetFiles().Length;
			return count;
		}

		public FileInfo GetLastFile(out bool DoesFileExists, string location)
		{
			DoesFileExists = (new DirectoryInfo(location).Exists);

			return (DoesFileExists) ? new DirectoryInfo(location).GetFiles().OrderByDescending(file => file.LastWriteTime).First() : null;
		}
	}
}
