using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Windows.Forms;
using System.Xml;

namespace Dynamic.Script_8DA875B9994CCA2
{
	// Script generated by Pega Robot Studio 19.1.112.0
	// Please use caution when modifying class name, namespace or attributes
	[OpenSpan.TypeManagement.DynamicTypeAttribute()]
	[OpenSpan.Design.ComponentIdentityAttribute("Script-8DA875B9994CCA2")]
	public sealed class Script
	{

	public  void DirectoryCopy(string strSource, string Copy_dest)
    {


	if (Directory.Exists(strSource))
{
    foreach (var file in new DirectoryInfo(strSource).GetFiles())
    {
        file.MoveTo($@"{Copy_dest}\{file.Name}");
    }
}


}
	
		public int GetFileCount(string SourcePath)
		{
			
			System.IO.DirectoryInfo dir = new System.IO.DirectoryInfo(SourcePath);
			int count = dir.GetFiles().Length;
			return count;
		}

		public FileInfo GetLastFile(out bool DoesFileExists, string location)
		{
			DoesFileExists = (new DirectoryInfo(location).Exists);

			return (DoesFileExists) ? new DirectoryInfo(location).GetFiles().OrderByDescending(file => file.LastWriteTime).First() : null;
		}

		public DataTable InputExcelData()
		{
			DataTable dt = new DataTable();
            dt.Columns.Add("SupplierID");
            dt.Columns.Add("SupplierName");
			 dt.Columns.Add("SecretServerName");
			
			DataRow dr1 = dt.NewRow();
			 dr1["SupplierID"] = "106119";
             dr1["SupplierName"] =  "KENERGY";
			  dr1["SecretServerName"] =  "KENERGY";
             dt.Rows.Add(dr1);

			 DataRow dr2 = dt.NewRow();
			 dr2["SupplierID"] = "104830";
             dr2["SupplierName"] =  "DEEP EAST TEXAS ELECTRIC COOP INC";
			  dr2["SecretServerName"] =  "DEEP EAST TEXAS 650285";
             dt.Rows.Add(dr2);


			 DataRow dr3 = dt.NewRow();
			 dr3["SupplierID"] = "104830";
             dr3["SupplierName"] =  "DEEP EAST TEXAS ELECTRIC COOP INC";
			  dr3["SecretServerName"] =  "DEEP EAST TEXAS 650269";
             dt.Rows.Add(dr3);


			 DataRow dr4 = dt.NewRow();
			 dr4["SupplierID"] = "104830";
             dr4["SupplierName"] =  "DEEP EAST TEXAS ELECTRIC COOP INC";
			  dr4["SecretServerName"] =  "DEEP EAST TEXAS 650293";
             dt.Rows.Add(dr4);

			 DataRow dr5 = dt.NewRow();
			 dr5["SupplierID"] = "104830";
             dr5["SupplierName"] =  "DEEP EAST TEXAS ELECTRIC COOP INC";
			  dr5["SecretServerName"] =  "DEEP EAST TEXAS 650307";
             dt.Rows.Add(dr5);


			 DataRow dr6 = dt.NewRow();
			 dr6["SupplierID"] = "104830";
             dr6["SupplierName"] =  "DEEP EAST TEXAS ELECTRIC COOP INC";
			  dr6["SecretServerName"] =  "DEEP EAST TEXAS 650315";
             dt.Rows.Add(dr6);

			 DataRow dr7 = dt.NewRow();
			 dr7["SupplierID"] = "104830";
             dr7["SupplierName"] =  "DEEP EAST TEXAS ELECTRIC COOP INC";
			  dr7["SecretServerName"] =  "DEEP EAST TEXAS 650323";
             dt.Rows.Add(dr7);

			  DataRow dr8 = dt.NewRow();
			 dr8["SupplierID"] = "104830";
             dr8["SupplierName"] =  "DEEP EAST TEXAS ELECTRIC COOP INC";
			  dr8["SecretServerName"] =  "DEEP EAST TEXAS 650331";
             dt.Rows.Add(dr8);

			 
			 DataRow dr9 = dt.NewRow();
			 dr9["SupplierID"] = "102951";
             dr9["SupplierName"] =  "CLECO POWER LLC";
			  dr9["SecretServerName"] =  "CLECO POWER APINQUIRY1";
             dt.Rows.Add(dr9);

			 DataRow dr10 = dt.NewRow();
			 dr10["SupplierID"] = "102951";
             dr10["SupplierName"] =  "CLECO POWER LLC";
			  dr10["SecretServerName"] =  "CLECO POWER APINQUIRY";
             dt.Rows.Add(dr10);
			 
			  DataRow dr11 = dt.NewRow();
			 dr11["SupplierID"] = "117682";
             dr11["SupplierName"] =  "ENTERGY LOUISIANA LLC";
			  dr11["SecretServerName"] =  "ENTERGY";
             dt.Rows.Add(dr11);

			  DataRow dr12 = dt.NewRow();
			 dr12["SupplierID"] = "104780";
             dr12["SupplierName"] =  "SOUTHWESTERN ELECTRIC POWER CO";
			  dr12["SecretServerName"] =  "SWEPCO";
             dt.Rows.Add(dr12);

			 return dt;

	   }


	   public string InserdataDBString(string strSupplierNo,string strName,string strSecretName,string strAccNo,string strDueDate,string strInvno,string strStatus,string strErrDesc)
	{
	string strTime = string.Empty;
	strTime = DateTime.Now.ToString("HH:mm:ss tt");
	string strDate = string.Empty;
	 strDate = DateTime.Now.ToString("dd-MMM-yyyy");

	string strInsertString = "INSERT INTO pegaapinv.pega_bot_logfile (RUN_DATE, RUN_TIME, SUPPLIER_NUMBER, SUPPLIER_NAME,SECRET_SERVER_NAME,ACCOUNT_NUMBER,INVOICE_NUMBER,CONTROL_DATE,AMOUNT,STATUS,ERROR) VALUES ('" + strDate + "', '" + strTime + "', '" + strSupplierNo + "','" + strName + "','" + strSecretName + "','" + strAccNo + "',  '" + strInvno + "', '" + strDueDate + "' ,'','" + strStatus+  "','" + strErrDesc + "'  )" ;
	
	return strInsertString;
	}

	 public string SelectDueDate(string strAccountNumber,string strDueDate)
	{
	
	string strSelectString = string.Empty;
	strSelectString =  "select * from pega_bot_logfile where account_number = '" + strAccountNumber + "' and control_date = '" + strDueDate + "'" ;

	return strSelectString;
	}
	


	   }
}
