using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Windows.Forms;
using System.Xml;

namespace Dynamic.Script_8D8CDCC34D01F1E
{
	// Script generated by Pega Robot Studio 19.1.18.0
	// Please use caution when modifying class name, namespace or attributes
	[OpenSpan.TypeManagement.DynamicTypeAttribute()]
	[OpenSpan.Design.ComponentIdentityAttribute("Script-8D8CDCC34D01F1E")]
	public sealed class Script
	{
		public int FileCount(string SourcePath)
		{
			System.IO.DirectoryInfo dir = new System.IO.DirectoryInfo(SourcePath);
			int count = dir.GetFiles().Length;
			return count;
		}
	}
}
