using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Windows.Forms;
using System.Xml;

namespace Dynamic.Script_8DA8CFB92D8BD2E
{
	// Script generated by Pega Robot Studio 19.1.112.0
	// Please use caution when modifying class name, namespace or attributes
	[OpenSpan.TypeManagement.DynamicTypeAttribute()]
	[OpenSpan.Design.ComponentIdentityAttribute("Script-8DA8CFB92D8BD2E")]
	public sealed class Script
	{
		public void NewMethod1()
		{
			// Add your code here...
		}
	}
}
