using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Windows.Forms;
using System.Xml;

namespace Dynamic.Script_8DA8C1149D8E1CC
{
	// Script generated by Pega Robot Studio 19.1.112.0
	// Please use caution when modifying class name, namespace or attributes
	[OpenSpan.TypeManagement.DynamicTypeAttribute()]
	[OpenSpan.Design.ComponentIdentityAttribute("Script-8DA8C1149D8E1CC")]
	public sealed class Script
	{

	public string InputExcelFile(DataTable dt , int indexrow )
	{
	string name = string.Empty;

     name = dt.Rows[indexrow]["Secret Server Name"].ToString();


return name;
	}

	public string InserdataString(string strSupplierNo,string strName,string strSecretName,string strAccNo,string strDueDate,string strInvno,string strStatus,string strErrDesc)
	{
	
	string strInsertString = "INSERT INTO pegaapinv.pega_bot_logfile (RUN_DATE, RUN_TIME, SUPPLIER_NUMBER, SUPPLIER_NAME,SECRET_SERVER_NAME,ACCOUNT_NUMBER,INVOICE_NUMBER,CONTROL_DATE,AMOUNT,STATUS,ERROR) VALUES (sysdate, '', '" + strSupplierNo + "','" + strName + "','" + strSecretName + "','" + strAccNo + "',  '" + strDueDate + "', '' ,'" +strInvno + "','" + strStatus+  "','" + strErrDesc + "'  )" ;

	return strInsertString;
	}
		public DataTable AddData()
		{
			DataTable dt = new DataTable();
            dt.Columns.Add("SecretSerName");
            dt.Columns.Add("UserName");
			 dt.Columns.Add("PassWord");
			 dt.Columns.Add("URL");
            
			DataRow dr1 = dt.NewRow();
			 dr1["SecretSerName"] = "DEEP EAST TEXAS 650285";
             dr1["UserName"] =  "650285002";
			  dr1["PassWord"] =  "6502855";
			   dr1["URL"] = "https://billing.deepeast.com/onlineportal/Customer-Login";
             dt.Rows.Add(dr1);

			

			 DataRow dr2 = dt.NewRow();
			 dr2["SecretSerName"] = "DEEP EAST TEXAS 650269";
             dr2["UserName"] =  "650269001";
			  dr2["PassWord"] =  "Boardwalk1";
			   dr2["URL"] = "https://billing.deepeast.com/onlineportal/Customer-Login";
             dt.Rows.Add(dr2);

			 DataRow dr3 = dt.NewRow();
			 dr3["SecretSerName"] = "DEEP EAST TEXAS 650293";
             dr3["UserName"] =  "650293004GSP";
			  dr3["PassWord"] =  "Boardwalk1";
			   dr3["URL"] = "https://billing.deepeast.com/onlineportal/Customer-Login";
             dt.Rows.Add(dr3);

			 DataRow dr4 = dt.NewRow();
			 dr4["SecretSerName"] = "DEEP EAST TEXAS 650307";
             dr4["UserName"] =  "650307001GSP";
			  dr4["PassWord"] =  "Boardwalk1";
			   dr4["URL"] = "https://billing.deepeast.com/onlineportal/Customer-Login";
             dt.Rows.Add(dr4);

			 DataRow dr5 = dt.NewRow();
			 dr5["SecretSerName"] = "DEEP EAST TEXAS 650315";
             dr5["UserName"] =  "650315001";
			  dr5["PassWord"] =  "Boardwalk1";
			   dr5["URL"] = "https://billing.deepeast.com/onlineportal/Customer-Login";
             dt.Rows.Add(dr5);

			 DataRow dr6 = dt.NewRow();
			 dr6["SecretSerName"] = "DEEP EAST TEXAS 650323";
             dr6["UserName"] =  "650323001";
			  dr6["PassWord"] =  "Boardwalk1";
			   dr6["URL"] = "https://billing.deepeast.com/onlineportal/Customer-Login";
             dt.Rows.Add(dr6);

			 DataRow dr7 = dt.NewRow();
			 dr7["SecretSerName"] = "DEEP EAST TEXAS 650331";
             dr7["UserName"] =  "650331002GSP";
			  dr7["PassWord"] =  "Boardwalk1";
			   dr7["URL"] = "https://billing.deepeast.com/onlineportal/Customer-Login";
             dt.Rows.Add(dr7);

			 DataRow dr8 = dt.NewRow();
			 dr8["SecretSerName"] = "CLECO POWER APINQUIRY";
             dr8["UserName"] =  "apinquiry";
			  dr8["PassWord"] =  "Boardwalk1!";
			   dr8["URL"] = "https://myaccount.cleco.com/web/guest/my-account";
             dt.Rows.Add(dr8);

			 DataRow dr9 = dt.NewRow();
			 dr9["SecretSerName"] = "CLECO POWER APINQUIRY1";
             dr9["UserName"] =  "apInquiry1";
			  dr9["PassWord"] =  "Boardwalk1!";
			   dr9["URL"] = "https://myaccount.cleco.com/web/guest/my-account";
             dt.Rows.Add(dr9);

			  DataRow dr10 = dt.NewRow();
			 dr10["SecretSerName"] = "ENTERGY";
             dr10["UserName"] =  "apinquiry@bwpipelines";
			  dr10["PassWord"] =  "BoardWalk";
			   dr10["URL"] = "https://myebusiness.entergy.com/maw/login.portal";
             dt.Rows.Add(dr10);

			   DataRow dr11 = dt.NewRow();
			 dr11["SecretSerName"] = "SWEPCO";
             dr11["UserName"] =  "apinvoices@bwpmlp.com";
			  dr11["PassWord"] =  "Boardwalk1";
			   dr11["URL"] = "https://www.swepco.com/";
             dt.Rows.Add(dr11);

			   DataRow dr12 = dt.NewRow();
			 dr12["SecretSerName"] = "KENERGY";
             dr12["UserName"] =  "APInquiry@bwpipelines.com";
			  dr12["PassWord"] =  "boardWalk#1";
			   dr12["URL"] = "https://kenergycorp.smarthub.coop/Login.html";
             dt.Rows.Add(dr12);

			 return dt;
		}
	}
}
